users = User.create(
  [
    { email: 'a@a.com', password: "a", password_confirmation: "a"},
    { email: 'b@b.com', password: "b", password_confirmation: "b"},
    { email: 'c@c.com', password: "c", password_confirmation: "c"},
    { email: 'd@d.com', password: "d", password_confirmation: "d"},
    { email: 'e@e.com', password: "e", password_confirmation: "e"},
    { email: 'f@f.com', password: "f", password_confirmation: "f"},
    { email: 'g@g.com', password: "g", password_confirmation: "g"},
    { email: 'h@h.com', password: "h", password_confirmation: "h"},
    { email: 'i@i.com', password: "i", password_confirmation: "i"},
    { email: 'j@j.com', password: "j", password_confirmation: "j"},
    { email: 'k@k.com', password: "k", password_confirmation: "k"},
    { email: 'l@l.com', password: "l", password_confirmation: "l"},
    { email: 'm@m.com', password: "m", password_confirmation: "m"},
    { email: 'n@n.com', password: "n", password_confirmation: "n"},
    { email: 'o@o.com', password: "o", password_confirmation: "o"},
    { email: 'p@p.com', password: "p", password_confirmation: "p"},
    { email: 'q@q.com', password: "q", password_confirmation: "q"},
    { email: 'r@r.com', password: "r", password_confirmation: "r"},
    { email: 's@s.com', password: "s", password_confirmation: "s"},
    { email: 't@t.com', password: "t", password_confirmation: "t"},
    { email: 'u@u.com', password: "u", password_confirmation: "u"},
    { email: 'v@v.com', password: "v", password_confirmation: "v"},
    { email: 'w@w.com', password: "w", password_confirmation: "w"},
    { email: 'x@x.com', password: "x", password_confirmation: "x"},
    { email: 'y@y.com', password: "y", password_confirmation: "y"},
    { email: 'z@z.com', password: "z", password_confirmation: "z"}
  ]
)

owners = Owner.create(
  [
    { first: "Alex", last: "Henry", zipcode: 12634, user_id: 1},
    { first: "Brad", last: "Pitman", zipcode: 66134, user_id: 2},
    { first: "Callie", last: "Cosby", zipcode: 99991, user_id: 3},
    { first: "Dorothy", last: "George", zipcode: 13622, user_id: 4},
    { first: "E", last: "Jones", zipcode: 11111, user_id: 5},
    { first: "F", last: "Smith", zipcode: 22222, user_id: 6},
    { first: "G", last: "Jones", zipcode: 11111, user_id: 7},
    { first: "H", last: "Smith", zipcode: 22222, user_id: 8},
    { first: "I", last: "Jones", zipcode: 11111, user_id: 9},
    { first: "J", last: "Smith", zipcode: 22222, user_id: 10},
    { first: "K", last: "Jones", zipcode: 11111, user_id: 11},
    { first: "L", last: "Smith", zipcode: 22222, user_id: 12},
    { first: "M", last: "Jones", zipcode: 11111, user_id: 13},
    { first: "N", last: "Smith", zipcode: 22222, user_id: 14},
    { first: "O", last: "Jones", zipcode: 11111, user_id: 15},
    { first: "P", last: "Smith", zipcode: 22222, user_id: 16},
    { first: "Q", last: "Jones", zipcode: 11111, user_id: 17},
    { first: "R", last: "Smith", zipcode: 22222, user_id: 18},
    { first: "S", last: "Jones", zipcode: 11111, user_id: 19},
    { first: "T", last: "Smith", zipcode: 22222, user_id: 20},
    { first: "U", last: "Jones", zipcode: 11111, user_id: 21},
    { first: "V", last: "Smith", zipcode: 22222, user_id: 22},
    { first: "W", last: "Jones", zipcode: 11111, user_id: 23},
    { first: "X", last: "Smith", zipcode: 22222, user_id: 24},
    { first: "Y", last: "Jones", zipcode: 11111, user_id: 25},
    { first: "Z", last: "Smith", zipcode: 22222, user_id: 0}
  ]
)

pets = Pet.create(
  [
    { name: "Fido", description: "dog_1", filename: "1.jpg", owner_id: owners[1].id},
    { name: "Dingo", description: "dog2", filename: "2.jpg", owner_id: owners[2].id},
    { name: "Bongo", description: "dog3", filename: "3.jpg", owner_id: owners[1].id},
    { name: "Fido", description: "Cdog_2", filename: "4.jpg", owner_id: owners[1].id},
    { name: "Dingo", description: "dog2", filename: "5.jpg", owner_id: owners[2].id},
    { name: "Bongo", description: "dog3", filename: "6.jpg", owner_id: owners[7].id},
    { name: "Fido", description: "Cdog_3", filename: "7.jpg", owner_id: owners[3].id},
    { name: "Dingo", description: "dog2", filename: "8.jpg", owner_id: owners[4].id},
    { name: "Bongo", description: "dog3", filename: "9.jpg", owner_id: owners[1].id},
    { name: "Fido", description: "Cdog_4", filename: "10.jpg", owner_id: owners[5].id},
    { name: "Bongo", description: "dog3", filename: "13.jpg", owner_id: owners[8].id},
    { name: "Fido", description: "Cdog_5", filename: "14.jpg", owner_id: owners[9].id},
    { name: "Dingo", description: "dog2", filename: "15.jpg", owner_id: owners[10].id},
    { name: "Bongo", description: "dog3", filename: "16.jpg", owner_id: owners[11].id},
    { name: "Fido", description: "Cdog_6", filename: "17.jpg", owner_id: owners[10].id},
    { name: "Dingo", description: "dog2", filename: "18.jpg", owner_id: owners[10].id},
    { name: "Bongo", description: "dog3", filename: "19.jpg", owner_id: owners[11].id},
    { name: "Fido", description: "Cdog_7", filename: "20.jpg", owner_id: owners[12].id},
    { name: "Dingo", description: "dog2", filename: "21.jpg", owner_id: owners[13].id},
    { name: "Bongo", description: "dog3", filename: "22.jpg", owner_id: owners[14].id},
    { name: "Fido", description: "Cdog_8", filename: "23.jpg", owner_id: owners[15].id},
    { name: "Bongo", description: "dog3", filename: "25.jpg", owner_id: owners[17].id},
    { name: "Fido", description: "Cdog_9", filename: "26.jpg", owner_id: owners[18].id},
    { name: "Dingo", description: "dog2", filename: "27.jpg", owner_id: owners[19].id},
    { name: "Bongo", description: "dog3", filename: "28.jpg", owner_id: owners[20].id},
    { name: "Fido", description: "Cdog_10", filename: "29.jpg", owner_id: owners[20].id},
    { name: "Dingo", description: "dog2", filename: "30.jpg", owner_id: owners[20].id},
    { name: "Bongo", description: "dog3", filename: "31.jpg", owner_id: owners[21].id},
    { name: "Bongo", description: "dog3", filename: "34.jpg", owner_id: owners[24].id},
    { name: "Fido", description: "Cdog_12", filename: "35.jpg", owner_id: owners[24].id},
    { name: "Dingo", description: "dog2", filename: "36.jpg", owner_id: owners[25].id},
    { name: "Bongo", description: "dog3", filename: "37.jpg", owner_id: owners[0].id},
  ]
)

posts = Post.create(
  [
    { post_type: "found", owner_id: owners[1].id, pet_id: 1},
    { post_type: "found", owner_id: owners[3].id, pet_id: 2},
    { post_type: "found", owner_id: owners[4].id, pet_id: 3},
    { post_type: "found", owner_id: owners[5].id, pet_id: 4},
    { post_type: "found", owner_id: owners[6].id, pet_id: 5},
    { post_type: "lost", owner_id: owners[7].id, pet_id: 6},
    { post_type: "lost", owner_id: owners[8].id, pet_id: 7},
    { post_type: "lost", owner_id: owners[9].id, pet_id: 8},
    { post_type: "lost", owner_id: owners[10].id, pet_id: 9},
    { post_type: "lost", owner_id: owners[11].id, pet_id: 10},
    { post_type: "lost", owner_id: owners[12].id, pet_id: 11},
    { post_type: "lost", owner_id: owners[13].id, pet_id: 12},
    { post_type: "lost", owner_id: owners[14].id, pet_id: 13},
    { post_type: "lost", owner_id: owners[15].id, pet_id: 14},
    { post_type: "lost", owner_id: owners[16].id, pet_id: 15},
    { post_type: "lost", owner_id: owners[17].id, pet_id: 16},
    { post_type: "lost", owner_id: owners[18].id, pet_id: 17},
    { post_type: "lost", owner_id: owners[19].id, pet_id: 18},
    { post_type: "lost", owner_id: owners[20].id, pet_id: 19},
    { post_type: "lost", owner_id: owners[21].id, pet_id: 20},
    { post_type: "found", owner_id: owners[22].id, pet_id: 21},
    { post_type: "found", owner_id: owners[23].id, pet_id: 22},
    { post_type: "found", owner_id: owners[24].id, pet_id: 23},
    { post_type: "found", owner_id: owners[25].id, pet_id: 24},
    { post_type: "found", owner_id: owners[0].id, pet_id: 25},
    { post_type: "found", owner_id: owners[7].id, pet_id: 26},
    { post_type: "found", owner_id: owners[8].id, pet_id: 28},
    { post_type: "found", owner_id: owners[9].id, pet_id: 29},
    { post_type: "found", owner_id: owners[0].id, pet_id: 30},
    { post_type: "found", owner_id: owners[1].id, pet_id: 31},
    { post_type: "found", owner_id: owners[2].id, pet_id: 32},
    { post_type: "found", owner_id: owners[3].id, pet_id: 27},
    { post_type: "found", owner_id: owners[4].id, pet_id: 3},
    { post_type: "found", owner_id: owners[5].id, pet_id: 4},
    { post_type: "found", owner_id: owners[16].id, pet_id: 5},
    { post_type: "found", owner_id: owners[17].id, pet_id: 6},
    { post_type: "found", owner_id: owners[18].id, pet_id: 17},
    { post_type: "found", owner_id: owners[19].id, pet_id: 18},
  ]
)
